# -*- coding: utf-8 -*-
"""
Base de donnees des livres pour "Librarian: Tidy Up the Arcane Library!"
Chaque section : etage, code, categorie (FR), couleur de l'etagere (FR),
puis des groupes de titres avec leur nombre de volumes (utile quand une
section melange des etageres de tailles differentes).
"""

SECTIONS = [
    # ----------------------------- ETAGE 1 -----------------------------
    {"floor": 1, "code": "1A", "cat": "Monstrologie",
     "color": "Brun / ton terreux sombre",
     "groups": [(10, [
        "The Illustrated Bestiary: Creatures of Land, Sky, and Sea",
        "Living with Monsters: A Guide to Care and Training",
        "Behavioral Patterns of Monsters",
        "Magical Creatures and Their Spells",
        "Monsterology: An Introduction to Forbidden Beast",
        "Ecological Pyramid of Monsters",
        "A Field Guide to Monsters: Identification and Survival",
        "Monsterology: Language and Vocal Patterns of Monsters",
        "A Pictorial Guide to the Ecology of Monsters",
        "Tears of the Beasts: Records of the Extinct and Forgotten",
        "Monster Field Notes: A Beastmaster's Journey",
        "The World Encyclopedia of Dragons",
     ])]},

    {"floor": 1, "code": "1B", "cat": "Astrologie & Divination",
     "color": "Bleu (fonce ou clair)",
     "groups": [(10, [
        "Prophecy of the Advent of the Great King of Terror",
        "Book of Constellations: The Thirteen Zodiac Signs That Guide Destiny",
        "Apocalypse of the Heavens, Omens and Warnings",
        "Voices of the Oracle: Revelations for the Chosen Listener",
        "One Right Guess in a Hundred Makes a Seer",
        "Prophecy by the Three Witches",
        "The Seer's Journal: Daily Visions of the Future",
        "The Abyss of Tarot: A Book of Symbols and Intuition",
        "Prophecy: Angelic Self-Writing",
        "The Art of Feng Shui: Reading Dragon Veins and Increasing Luck",
        "Animal Oracles: Prophesying Match Results",
        "The Crystal Tome: Practical Scrying and Clairvoyance",
     ])]},

    {"floor": 1, "code": "1C", "cat": "Maledictions & Contre-sorts",
     "color": "Noir avec rouge fonce",
     "groups": [
        (10, [
            "The Countercurse Compendium: Magic That Bites Back",
            "Seal and Sever: Lost Rites of Curse-Breaking",
            "The Dark Pact: The Birth of a Curse",
            "The Grand Compendium of Curses: 100 Hexes and 100 Dispells",
        ]),
        (3, [
            "Reverse Ritual Tracing for Curse Source Identification",
            "The Book of Curses: Forgotten Plagues and Their Dispells",
            "The Death's Note",
            "Advanced Curse Analysis: Multiple Structures and Dissolution Process",
            "Curse-Breaking Arithmancy and Sealing Arts",
            "The Lexicon of Curses: Malefic Words and Their Power",
            "Breaking the Curse of the Trophyless",
            "Introduction to Malediction Systems: Taxonomy, Structure, and Mechanisms",
        ]),
     ]},

    {"floor": 1, "code": "1D", "cat": "Barde & Musique",
     "color": "Vert ou tons terreux",
     "groups": [
        (10, [
            "A Collection of Chanted Verses: Status Buffing and Nerfing",
            "The Chronicle of World Music of Magic",
            "Spell Chanting Technique: The Blending of Sound and Spell",
            "The Dark Sonata: Music That Attracts Calamity",
        ]),
        (3, [
            "Transcendental Magic Etudes of Execution",
            "The Bard's Book of Spells",
            "Theoretical Foundations of Enchanted Music",
            "Magical Psalms: Methodology for Compiling Chanted Poetry",
            "Theory of Chanting: Principles of Mana Amplification via Voice",
            "Chanting Methods of Resonating with Natural Entities",
            "Musical Saint: A Great Figure Who Brought Music to the Masses",
            "Witches' Hymnal",
        ]),
     ]},

    {"floor": 1, "code": "1E", "cat": "Necromancie",
     "color": "Bleu fonce ou violet fonce",
     "groups": [(10, [
        "Theory of the Nether Strata: Analysis of the Afterworld",
        "How to Command the Army of the Dead",
        "Compendium of Necromancy: The Arts of Management and Maintenance",
        "Foundations of Necromancy: On the Fixation and Severance of Souls",
        "Night Parade of One Hundred Demons",
        "Ritual Design Guidelines for the Practicing Necromancer",
        "A Technique to Turn Wandering Ghosts into Servants",
        "Necrodefense Compendium: Dealing with Hauntings",
        "Compendium of Necromancy: The Beginner's Guide",
        "Practical Necromancy: Skeleton Edition",
        "Zombie: The Secret Rituals for Domination",
        "Rituals of Calling and Commanding the Dead",
     ])]},

    {"floor": 1, "code": "1F", "cat": "Metamorphose (Transfiguration)",
     "color": "Rouge fonce avec brun",
     "groups": [(10, [
        "Introduction to Inanimate Transfiguration",
        "Humanization: A Transformation Guide for Non-Humans",
        "The Codex of Transfiguration: Detection and Nullification",
        "Complete Practical Transfiguration: Phases and Sustaining Techniques",
        "Mastery of Mimicry: Theory and Practice of Visual Imitation",
        "Introduction to the Theory of Transfiguration",
        "Reducing Metamorphosis Time: How to Minimize Vulnerability",
        "Magical Physiology of Therianthropy",
        "Correlation of Transformation Duration and Mana Deplation",
        "Preservation of Mental Identity in Therianthropic Spells",
        "Foundations of Transformation: Object Alteration and Reassembly",
        "Beastification and the Threshold of Madness",
     ])]},

    {"floor": 1, "code": "1G", "cat": "Artefacts magiques & Enchantement",
     "color": "Bleu fonce vif ou violet fonce vif",
     "groups": [
        (10, [
            "The Grand Encyclopedia of Magical Artifacts",
            "Practical Enchantment: Offense and Defense Enhancement",
            "Magical Item's Workshop Series",
            "Foundations of Magical Item Crafting and Materials",
        ]),
        (3, [
            "The Inverse Law of High Grade Armor and Fabric Coverage",
            "Compendium of Forbidden Relics",
            "Crystal Catalog: Elemental Properties and Enchantment Mastery",
            "Forging Magical Items",
            "Repair and Returning of Enchanted Gear",
            "Introduction to Enchantment Theory",
            "The Magic Ring That Steals Reason",
            "Artifacts That Change The World",
        ]),
     ]},

    {"floor": 1, "code": "1H", "cat": "Furtivite (Stealth)",
     "color": "Noir",
     "groups": [
        (10, [
            "Codex of the Stealth Arts",
            "Stealth Techniques: Concealment Among Nearby Objects",
            "Hide vs Seek: Magical Warfare of Stealth and Detection",
            "Complete Guide to Stealth Magic",
        ]),
        (3, [
            "The Art of Hiding One's Presence",
            "The Art of Shadow Walking",
            "Introduction to Stealth Magic: The Art of Shadowing",
            "Stealth Arts: Techniques to Becoming Air",
            "The Book of Ninja: Lurking in the Darkness",
            "Shadowmages: Shadow Cloning and Teleportation",
            "Tactics of the Bucket: Vision-Sealing Theft",
            "Foundations and Applications of Invisibility Magic",
        ]),
     ]},

    {"floor": 1, "code": "1I", "cat": "Magie d'Illusion",
     "color": "Bleu fonce ou violet fonce",
     "groups": [(10, [
        "The Illusory Art: Sovereignty over the Five Senses",
        "The Infinite Hall: Creating Inescapable Illusory Spaces",
        "Chronostatic Illusions: Manipulating the Perception of Time",
        "Terror Illusions: Spells to Shatter the Enemy's Mind",
        "The Art of Illusion Defense: Mental Defences and Protection of the Five Senses",
        "Introduction to Illusion Magic: Truths of the Imaginary",
        "The Grand Compendium of Illusion Magic",
        "Illusion Magic: The Art of Hypnosis",
        "Where Illusion Ends and Reality Begins",
        "Crafting Visual and Auditory Illusions",
        "Enchanting Illusions: Seduction Magic",
        "The Ultimate Illusion: Mirror Flower, Water Moon",
     ])]},

    {"floor": 1, "code": "1J", "cat": "Magie d'Invocation",
     "color": "Bleu fonce",
     "groups": [(10, [
        "Theory and Practice of Hero Summoning from Another World",
        "A Beginner's Guide: Summoning the Useless Goddess",
        "Introduction to Summoning: Fundamentals of Otherworldly Contracts",
        "Summoning and Controlling Catastrophic Entities",
        "Summoning Magic for Beginners",
        "Magic Circles and Summoning Syntax Explained",
        "Trans-Temporal Summons and the Law of Causality",
        "Divine Dragon Summoning: Descent of Bahamut",
        "The Book of Summoning and Contracts",
        "Encyclopedia of 10,000 Summons: The Complete Collection from Heaven to the Abyss",
        "Succubus Summoning Techniques and Practical Applications",
        "The Complete Summoning Grimoire",
     ])]},

    {"floor": 1, "code": "1K", "cat": "Soigneur & Magie de soin",
     "color": "Blanc avec rouge",
     "groups": [(10, [
        "Introduction to Magical Healing",
        "The Four Principles of the Healer's Ethics",
        "Spells for Curing Poisons and Diseases",
        "Healing Magic for the Reclamation of Mind and Consciousness",
        "Fundamentals of Healing and Mana Control",
        "Advanced Healing Theory: Maintaining Vigor Until Daybreak",
        "The Grand Compendium of Healing Magic",
        "No More \"Healer Diff\": A Comprehensive Guide",
     ])]},

    {"floor": 1, "code": "1L", "cat": "Magie Sacree (Holy)",
     "color": "Blanc avec or",
     "groups": [(10, [
        "Selection and Application of Targets for Holy Magic",
        "Formation and Maintenance of Large Sacred Barriers",
        "Holy Magic: Undead Protection and Purification",
        "Prolegomena to Holy Magic Theory",
        "Compendium of Sacred Purification Magic",
        "Fundamentals of Holy Power in Undead Annihilation",
        "Theological Research on Holy Magic",
        "Spells of Holy Light for Concealing Vital Areas",
     ])]},

    {"floor": 1, "code": "1M", "cat": "Magie de Destruction",
     "color": "Couverture/dos avec gemmes colorees",
     "groups": [
        (10, [
            "Book of Spells: Water - Novice -",
            "Book of Spells: Wind - Novice -",
            "Book of Spells: Fire - Novice -",
            "Book of Spells: Earth - Novice -",
            "Book of Spells: Ice - Adept -",
            "Book of Spells: Thunder - Adept -",
            "Book of Spells: Shadow - Adept -",
            "Book of Spells: Light - Adept -",
            "Book of Spells: Dimension Rift - Expert -",
            "Book of Spells: Fluid - Expert -",
            "Book of Spells: Forest Creation - Expert -",
            "Book of Spells: Pulverization - Expert -",
        ]),
        (5, [
            "Book of Spells: Space - Legendary -",
            "Book of Spells: Explosion - Legendary -",
            "Book of Spells: Time - Legendary -",
            "Book of Spells: Energy - Legendary -",
            "Book of Spells: Gravitation - Master -",
            "Book of Spells: Matter Creation - Master -",
            "Book of Spells: Abyss - Master -",
            "Book of Spells: Psychokinesis - Master -",
        ]),
     ]},

    {"floor": 1, "code": "1N", "cat": "Alchimie & Potions",
     "color": "Embleme rond avec un arbre sur la couverture",
     "groups": [
        (10, [
            "The Alchemist's Field Guide: Natural Materials and Foraging",
            "The Alchemist's Encyclopedia: Categories and Efficacy of Ingredients",
            "Forbidden Alchemy: The Guide to Toxin Brewing and Disposal",
            "Alchemy Codex: An Introduction to Herbology",
            "Books of Alchemy: The Laws and Taboos of Chimera Synthesis",
            "Books of Alchemy: The Little Herbology of the Faefolk",
            "Books of Alchemy: The Ultimate Secret of the Philosopher's Stone",
            "Books of Alchemy: Homunculus - Chronicle of the Forbidden Creation",
            "Books of Alchemy: A Practical Guide to Potion Crafting",
            "Books of Alchemy: Potion Safety and Storage Manual",
            "Books of Alchemy: Practical Extraction of High-Purity Essences",
            "Books of Alchemy: Encyclopedia of World Potions",
        ]),
        (5, [
            "Tomes of Alchemy: Alchemical Tools and Laboratory Apparatus",
            "Tomes of Alchemy: Beginner Manual of Alchemical Synthesis",
            "Tomes of Alchemy: Complete Theory of Elemental Transmutation",
            "Tomes of Alchemy: The Great Compendium of Synthesis Recipes",
            "Tomes of Alchemy: Alchemical Safety Manual Handling Hazardous Materials",
            "Tomes of Alchemy: The Alchemical Art of Transmuting Food tot Poop",
            "Tomes of Alchemy: A Beginner's Guide to Modern Synthesis",
            "Tomes of Alchemy: A Grimoire of Elemental Fusion and Fission",
        ]),
     ]},

    # ----------------------------- ETAGE 2 -----------------------------
    {"floor": 2, "code": "2A", "cat": "Guerrier",
     "color": "Brun / rouge fonce (sauf 1 livre bleu)",
     "groups": [(10, [
        "The Supreme Creed: The Naked Warrior",
        "Mind Like Still Water: The Zen of Perfect Parrying",
        "The Weapon Compendium: Use of Swords, Axes and Spears",
        ("Armor and Muscle: Synergy Between Body and Steel", "Ce livre est le BLEU de la section"),
        "Scion of the Axe God: Strongest Warrior Chosen by the Sun",
        "Battlefield Logic: A Tactical Guide for Warriors",
        "Sword Saint: The One Who Sliced the Mountains",
        "Warrior's Foundation: Between Blade and Spell",
        "The Warrior's Creed: Only Cowards Become Long-Range Mages",
        "Blade: Dimension Slash Combat Technique",
        "Heretic Blade Arts: Three Sword Style",
        "The Dark Berserker and the Greatsworld",
     ])]},

    {"floor": 2, "code": "2B", "cat": "Tir a l'arc (Archery)",
     "color": "Vert",
     "groups": [(10, [
        "Applied Archery Tactics: Arrows of Stillness and Motion",
        "Anatomy of the Bow and Arrow",
        "The Grand Compendium of Archery",
        "The Hunter's Archery Manual",
        "Forging and Using Magical Bows",
        "From Longbow to Shortbow: Tactical Applications",
        "The Fundamentals of Archery: Spirit and Skill",
        "Arrow of the Shattered Knee",
        "The Book of Arcane Bows: Magic Infused Arrows",
        "Stellar Archery: Resonance of Stars and Arrows",
        "Archers of the Fairies Pact",
        "The Art of the Arrow Series",
     ])]},

    {"floor": 2, "code": "2C", "cat": "Magie du quotidien",
     "color": "Pastel",
     "groups": [
        (10, [
            "Minor Repairs: Practical Everyday Magic",
            "Magic Techniques to Boost Household Efficiency",
            "1000 Easy Spells to Use at Home",
            "A Compendium of Useless Magic from Around the World",
            "The Complete Guide to Everyday Magic: Simple Life Enchantments",
            "Introduction to LifeHack Magic",
        ]),
        (3, [
            "Storage Magic: Different Dimension Pocket",
            "What Kind of Magic Works Best for Job Hunting?",
            "Handy Kitchen Magic Recipes",
            "Home Magic: Spells to Protect and Nurture Your Dwelling",
            "Three Seconds to Office: Magic for Last-Minute Commuters",
            "Magic to Mute a Specific Person's Voice",
            "Magic to Speak and Convey",
            "How to Commute with Magic",
            "Broom Handling Techniques: The Art of Aerial Travel",
            "Compendium Magic for the Lazy",
            "Spoiler Prevention Magic",
            "Everyday Magic for Deep and Restful Sleep",
        ]),
     ]},

    {"floor": 2, "code": "2D", "cat": "Mathematiques",
     "color": "Couleurs variees (reconnaissables au logo sur le dos)",
     "groups": [
        (10, [
            "Easy Math! Magical Representation Theory for a 3-Year Old",
            "Theory of Everything: Grasping Beautiful Theory through Equations",
            "Mana Measurement and Conversion Equations",
            "Structural Analysis of Sorcerous Equations",
            "The Mathematical Geometry of Magic Circles",
            "Introduction to Sorcery Mathematics",
        ]),
        (3, [
            "Prophecy and Probability Theory",
            "Mass-Mana Equivalence",
            "Genesis Theory: An Interpretation via Imaginary Numbers",
            "Mathematical Methods for Constructing Magic Circles",
            "Magical Analysis Based on the Application of Infinite Series",
            "Prime Equation: The Absolute Order Hidden Behind Irregularity",
            "Arcane Glyphs and Pattern Theory",
            "Vector Space Theory of Magic",
            "Temporal Magic and Chaos Theory",
            "The Law of Equivalent Exchange",
            "Spatial Distribution of Mana Density and Its Fluctuation Characteristics",
            "Quantification of Cursed Power and Constraint Conditions",
        ]),
     ]},

    {"floor": 2, "code": "2E", "cat": "Art",
     "color": "Couleurs variees",
     "groups": [(10, [
        "Process: Sublimating Brain Fragments into Works",
        "Art Collection That No One Can Understand",
        "Introduction to Magical Art",
        "Living Paintings: Creating and Controlling Animated Magical Art",
        "How to Change Drawn Art into Reality",
        "Perfect Lines and Circles: The Secret to Drawing in One Stroke",
        "Art is Sublime Because It Has No Answer",
        "Drawing Moving Characters: Beginner Level",
        "Puppet Crafting: An Introductory Guide to Automata and Statues",
        "Art and Magic Circles: Definitions and Differences",
        "Techniques for Returning a Drawing to a Previous Step",
        "Memory Transfer: The Technique of Direct Scene Depiction from your Brain",
     ])]},

    {"floor": 2, "code": "2F", "cat": "Management",
     "color": "Bleu fonce",
     "groups": [(10, [
        "Conflict Protocols for Guilds",
        "Managing Diverse and Cross-Race Adventurer Parties",
        "Organizational Discipline: How Small Cracks Lead to Great Ruin",
        "Research of Adventurer Party Tactics Series",
        "Systems for Nurturing and Promotions in Guilds",
        "Guild Treasury and Reward System Management",
        "Magical Supply Chain Management",
        "Licensing and Regulation of Magic Users",
        "Management: Mana Resource Allocation and Optimization",
        "Management: High-Ranking Magician Training and Evaluation System",
        "Management: Tactical Command of Magical Forces",
        "Management: Administration of Magical Institutions",
     ])]},

    {"floor": 2, "code": "2G", "cat": "Economie",
     "color": "Vert",
     "groups": [
        (10, [
            "Introduction to Arcane Market Systems",
            "Arcane Economy Report: Regional Mana Market Analysis",
            "Magic and Value: Arcane Resource Valuations",
            "Economics: Wage Structures in the Magical Professions",
            "Mana Currency Systems and Their Evolution",
            "An Introduction to Magical Economics",
        ]),
        (3, [
            "Economics: The Revolution in Logistics Through Teleportation",
            "Alchemy and Inflation: The Gold Collapse",
            "Why Do Stocks Crash the Moment I Buy Them?",
            "The Complete Works of Magical Economics",
            "Studies in Arcane Fiscal Theory",
            "Economics: Where Did the Taxes Go?",
            "The Arcane Black Market and Price Manipulation",
            "Financial: The Art of the Tariff",
            "Economics: The Lost Three Decades",
            "History of Demonic Financial Hegemony",
            "Economics: Supply and Trade of Arcane Resources",
            "Spell Patents and IP Rights",
        ]),
     ]},

    {"floor": 2, "code": "2H", "cat": "Sociologie",
     "color": "Brun (rose fonce / orange fonce)",
     "groups": [
        (10, [
            "Labor Studies: Even with Magic, Overtime Never Ends",
            "Career Opportunity: Graduated from Magic University... Got Zero Job Offers",
            "Job Inequality: Low Salary even as a Licensed Sage",
            "Interracial Social Dynamics",
            "Work Culture: The Mage Who Changed Jobs to a Sweatshop",
            "The Influence of Short-Lived Cultures on Long-Lived Species",
        ]),
        (3, [
            "The Rift in Values Between Different Species with Differing Lifespans",
            "The Labor Reality of Mages: Unpaid and Unprotected Interns",
            "The Structure of Power Monopolization Tendencies by Long-Lived Species",
            "Wage Gaps: Universal Mana Income for Mages Now!",
            "\"Low Mana\" a Form of Discrimination?",
            "Marriage Is a Contract Spell: Advanced Disenchantment is required for Divorce",
            "Sociology: Mage Pension System on the Brink of Collapse",
            "A Media Society Manipulated by Magic",
            "How to Survive a Mana-Disparity Society",
            "Labor Studies: Where are the Workplaces to Apply Your University-Learned Magic?",
            "Mana and Labor: Sociology of Magical Economies",
            "Social Structures of Magical Civilizations",
        ]),
     ]},

    {"floor": 2, "code": "2I", "cat": "Psychologie",
     "color": "Rouge fonce",
     "groups": [(10, [
        "A Diary of the Change in the State of the Mind-Reading Girl",
        "A Psychologist's Definition of \"Happiness\": The Cutting Edge of Happiness Research",
        "The Psychology: Powerlessness and Responsibility Shifting",
        "The Psychology of Backseat Gaming",
        "Introduction to Psychological Principles and Analysis",
        "The Psychology of Using Strong Language from a Safe Zone",
        "Psychology: Mentality That the Weak Bark the Most",
        "Mind Reading: Detecting Lies through Facial Expressions and Gestures",
        "Effort Builds Confidence, and Confidence Leads to Action",
        "The Psychology of Prioritizing Gaming Over Tidying Your Room",
        "The Correlation of Magic and Emotion",
        "Ultimate Choice: Curry flavoured Poop, or Poop flavoured Curry?",
     ])]},

    {"floor": 2, "code": "2J", "cat": "Philosophie",
     "color": "Blanc",
     "groups": [(10, [
        "Philosophy of Science: Methodology and Truth",
        "Philosophy of Self and Other",
        "Soul, Mind, and Body: Are They Truly Distinct",
        "Philosophy: Power and Ethics",
        "Philosophy of Mana and Willpower",
        "Fantasy or Reality? The Ontological Problem of World",
        "Ethics of Magic: Responsibility and Restraint",
        "Teachings of the Great Philosophers of Magic",
        "Philosophical Studies in Magic",
        "Foundations of Metaphysics",
        "Introduction to Magical Determinism: Spell-Causality and the Philosophy",
        "I think, therefore I am",
     ])]},

    {"floor": 2, "code": "2K", "cat": "Droit (Jurisprudence)",
     "color": "Vert fonce ou bleu",
     "groups": [
        (10, [
            "Grand Compendium of Magic Jurisprudence",
            "The System and Precedents of the Arcane Court",
            "The Constitution of the Kingdom",
            "Chronicles of the Magical Court",
            "Law: Foundations of Contemporary Magical Jurisprudence",
            "Codex of Truth Verification",
        ]),
        (3, [
            "Comparative Study of National Magic Laws",
            "Legal Treatment of Forbidden Magic",
            "Monster Hunting Law: List of Prohibited Species and Regulation of Attack Methods",
            "Contract Law: How to Write Adventurer Contracts",
            "Civil Liability Within Adventuring Parties",
            "Legality and Regulation of Magic Use",
            "Legal System for Magical Accidents and Accountability",
            "Magical Detective Law: Punishment Act for the Use of Unapproved and Unregistered Spell",
            "Guild Charter: Guild Discipline and Expulsion Systems",
            "The Idea of Equality Under the Law Is Laughable",
            "The Legalities of Party Disbandment: Property Distribution and Liability",
            "Compendium of Magical Civil Law: Definition of Personhood, Rights and Succession",
        ]),
     ]},

    {"floor": 2, "code": "2L", "cat": "Romans d'amour",
     "color": "Couleurs variees (souvent rose)",
     "groups": [
        (10, [
            "Romance Novel: A Pact Beneath the Stars",
            "Romance Novel: The Fire King and the Ice Queen",
            "Romance Novel: Senior and the Beast",
            "Romance Novel: Whispers of the Moon",
            "A Midsummer Night's Sweet Dream",
            "A Kiss Wrought in Spells",
        ]),
        (3, [
            "True Love between A 20-Year-Old Lady and an 80-Year-Old Tycoon",
            "30 year old Wizard's First Love",
            "The Witch and the Accidental Love Potion",
            "The Strongest Archmage is Obsessed with Me, the Girl with Zero Magic!",
            "Cursed to Love You",
            "Roses Are Red, Violets Are Blue",
            "Fill The Solitude of My Millennium with Your Ninety Years",
            "Romance Novel: The Red Lady and the Bamboozled Men",
            "Romance Novel: The Chicken and The Cat",
            "Romance Novel: My Massive Golden Balls",
            "Romance Novel: Lies More Beautiful Than Truth",
            "Romance Novel: The Thorn Prince",
        ]),
     ]},

    {"floor": 2, "code": "2M", "cat": "Romans policiers",
     "color": "(couleur non precisee)",
     "groups": [
        (10, [
            "The Arcane Detective Files",
            "Detective the Reaper",
            "Mystery Fiction: The Bloodstained Astrologer",
            "Mystery Fiction: The Prospero Code",
        ]),
        (5, [
            "Mystery Fiction: One Who Looks into the Abyss",
            "Mystery Fiction: The Pirate Captain Who Stepped Down from His Ship",
            "Mystery Fiction: Judgment of the Spectral Tribunal",
            "Mystery Fiction: Magical Theorist Maris",
        ]),
     ]},

    {"floor": 2, "code": "2N", "cat": "Histoire",
     "color": "Rouge / violet / orange fonce (1 livre bleu fonce)",
     "groups": [
        (10, [
            "Studies in the History of Magical Civilizations",
            "The Genesis of Magic and the Evolution of Civilization",
            "Origins of Magic: Awakening of the First Spells and Magic Power",
            "The Transition and Evolutionary History of Magic",
        ]),
        (5, [
            "Record of the Demon King's Subjugation: The Archmage's Conquest",
            "The History of World Exploration and the Discovery of Lost Continents",
            "Ancient Manuscript Studies on Mage Birth",
            "History and Tactics of Magical Warfare",
        ]),
     ]},

    {"floor": 2, "code": "2O", "cat": "Voyages dans l'autre monde",
     "color": "(couleur non precisee)",
     "groups": [
        (10, [
            "The Cursed Workplaces of a Magicless World",
            "They Call Their Mana \"Dark Energy\"",
            "A People Enchanted by Glowing Slabs",
            "The Curious Daily Life in a World Without Magic",
        ]),
        (5, [
            "The Ultimate Guide to Otherworldly Swear Words",
            "Otherworld Chronicles: A World Ruled by Data",
            "They Worship an Invisible Entity Known as Wi-Fi",
            "The Otherworld: Demanding Fresh Graduates with 10 Years of Experience",
            "The \"Internet\": The All-Knowing Grimoire",
            "Strange Technology from Another World! The Ultimate Language: C++",
            "A World Without a Demon Lord, Yet Full of Corporate Slaves",
            "In the Otherworld, Money is the Ultimate Magic",
        ]),
     ]},

    {"floor": 2, "code": "2P", "cat": "Donjons",
     "color": "Violet clair ou rose fonce",
     "groups": [
        (10, [
            "Compendium of Dungeon Resources",
            "Dungeon of the Abyss",
            "Bestiary Components: Dungeon Creatures",
            "Fundamentals of Dungeon Architecture",
        ]),
        (5, [
            "Gourmet Expeditions in the Dungeon",
            "Practical Dungeon Tactics",
            "The Daily Dungeon Notes of the Party Chronicler",
            "Optimization Theory of Dungeon Routes",
        ]),
     ]},

    {"floor": 2, "code": "2Q", "cat": "Langues",
     "color": "Rouge fonce et vert (couleurs de Noel), 1 livre bleu",
     "groups": [
        (10, [
            "Everyone's Fairy Tongue: Tiny and Lovely Words",
            "Everyone's Demonic: Words of Covenant and Power",
            "Everyone's Elvish: The Graceful Speech of the Forest",
            "Everyone's Dwarvish: The Craftsman's Language",
        ]),
        (5, [
            "Inter-Species Communication",
            "The Language of Draconic: Roars of Ancient Wisdom and Primal Power",
            "How Did the First Language Emerge? The Origins of Language Evolution",
            "The Birth of Magical Languages: Secrets of Spells and Ancient Speech",
        ]),
     ]},
]


def build_books():
    """Aplati SECTIONS en une liste de livres avec toutes les metadonnees."""
    books = []
    for sec in SECTIONS:
        for vol, titles in sec["groups"]:
            for t in titles:
                note = ""
                if isinstance(t, tuple):
                    t, note = t
                books.append({
                    "title": t,
                    "floor": sec["floor"],
                    "section": sec["code"],
                    "cat": sec["cat"],
                    "color": sec["color"],
                    "vol": vol,
                    "note": note,
                })
    return books


BOOKS = build_books()

if __name__ == "__main__":
    print(f"Total livres : {len(BOOKS)}")
    from collections import Counter
    c = Counter(b["section"] for b in BOOKS)
    for k in sorted(c):
        print(k, c[k])
